[package]
name = "raze"
version = "0.1.11"
authors = ["Kongou <kongou@shipfu.moe>"]
description = "A library for accessing and using the BackBlaze B2 API. Includes raw API calls and an easy-to-use struct"
keywords = ["b2", "api", "backup", "backblaze"]
categories = ["api-bindings"]
exclude = ["credentials"]
readme = "README.md"
repository = "https://github.com/KongouDesu/raze"
license = "MIT"


[dependencies]
reqwest = "0.8.6"
base64 = "0.9.2"
hyper = "0.11.9"
url = "1.7.0"

serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

[dependencies.sha1]
version = "0.6.0"
features = ["std"]